version: '3.9'
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: dbt
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    # TODO: if you want to run make test you'll need to get psql and
    # pytest working on this container, maybe make your own Dockerfile?
    # NOTE: running things on this container is WAY slower than running
    # locally for some reason. It seems to be bottled by CPU, based on
    # the output of docker stats?
    build: .
    container_name: dbt
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - ./dbt_config:/root/.dbt  # Mount the profiles.yml directory

volumes:
  postgres_data:

