services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: user
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: dbt,metabaseappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres_mount:/docker-entrypoint-initdb.d

  dbt:
    # NOTE: running things on this container is WAY slower than running
    # locally for some reason. It seems to be bottled by CPU, based on
    # the output of docker stats?
    build: .
    container_name: dbt
    platform: linux/amd64
    depends_on:
      - postgres
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:

