version: '3.9'
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: dbt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

