marmot:
  target: dev
  outputs:
    dev:
      dbname: dbt
      # Note: swap localhost out for postgres if you're running this inside
      # of docker. I am bad at docker stuff and can't figure out an easy way
      # to modify this based on whether you're running this in docker vs on
      # the host itself :p.
      # I'm getting like 10x slower dbt runs in docker and can't debug it
      # in 30 minutes so I'm just gonna stop for now.
      host: postgres
      pass: user
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: user


