marmot:
  target: dev
  outputs:
    dev:
      dbname: dbt
      # I'm getting like 10x slower dbt runs in docker and can't
      # figure out why :/
      host: "{{ env_var('MARMOT_DB_HOST', 'localhost') }}"
      pass: user
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: user


