on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: run ci lint + tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build the stack
        run: docker compose up -d
      - name: lint
        run: docker exec marmot_dbt make lint
      - name: test
        run: docker exec marmot_dbt make test

