on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: sqlfluff lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build the stack
        uses: docker-compose up -d
      - name: sqlfluff
        uses: docker compose run dbt sqlfluff lint

